---
title: "Lung Cancer LN check the APOE high myeloid cell function 02-10-2025"
output: html_notebook
---

```{r}
library(Seurat)
library(dplyr)
library(ggplot2)
library(clusterProfiler)
library(enrichplot)
library(msigdbr)
library(stringr)
```


```{r}
path <- "~/projects/2023/GY_Park/Lung_cancer/All_sample/"
LN.immune <- readRDS(file = paste0(path,"/upload_data/LN_immune_082024.rds"))
LN.immune <- ScaleData(LN.immune, features = rownames(LN.immune))
```

```{r}
DimPlot(LN.immune)
```


```{r}
# All.markers.APOE_high <- FindMarkers(LN.immune, ident.1 = "APOE high myeloid cells", test.use = "MAST", logfc.threshold = 0.1, verbose = F, min.pct = 0.1)
# All.markers.FNC1_high <- FindMarkers(LN.immune, ident.1 = "FCN1 high myeloid cells", test.use = "MAST", logfc.threshold = 0.1, verbose = F, min.pct = 0.1)
# All.markers.HLA_DQA1_high <- FindMarkers(LN.immune, ident.1 = "HLA-DQA1 high myeloid cells", test.use = "MAST", logfc.threshold = 0.1, verbose = F, min.pct = 0.1)
```


# GSEA
```{r}
set.seed(2025)
hallmark_geneset <- msigdbr(species = "Homo sapiens",  category = "H")
head(hallmark_geneset)
hallmark_geneset$gs_name_short <- str_extract(hallmark_geneset$gs_name, "(?<=HALLMARK_).*$")
```

# APOE high
```{r}
# sort_glist <- All.markers.APOE_high$avg_log2FC
# names(sort_glist) <- rownames(All.markers.APOE_high)
# sort_glist <- sort(sort_glist, decreasing = T)
# gsea_All.APOE_high <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T)
```

```{r}
# dotplot(gsea_All.APOE_high, showCategory=10, split=".sign") + facet_grid(.~.sign)
```

# FCN1 high
```{r}
# sort_glist <- All.markers.FNC1_high$avg_log2FC
# names(sort_glist) <- rownames(All.markers.FNC1_high)
# sort_glist <- sort(sort_glist, decreasing = T)
# gsea_All.FNC1_high <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T)
```

```{r}
# dotplot(gsea_All.FNC1_high, showCategory=10, split=".sign") + facet_grid(.~.sign)
```

# HLA-DQA1 high
```{r}
# sort_glist <- All.markers.HLA_DQA1_high$avg_log2FC
# names(sort_glist) <- rownames(All.markers.HLA_DQA1_high)
# sort_glist <- sort(sort_glist, decreasing = T)
# gsea_All.HLA_DQA1_high <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T)
```

```{r}
# dotplot(gsea_All.HLA_DQA1_high, showCategory=10, split=".sign") + facet_grid(.~.sign)
```

# Myeloid subset
```{r}
Myeloids <- subset(LN.immune, idents = c("APOE high myeloid cells", "FCN1 high myeloid cells", "HLA-DQA1 high myeloid cells"))
```

```{r}
DimPlot(Myeloids)
```

```{r}
tm <- subset(Myeloids, subset = Control_Cancer == "Control")
DimPlot(tm)
table(tm$anno_update)
```


```{r}
tm <- subset(Myeloids, subset = Control_Cancer == "Metastatic")
DimPlot(tm)
table(tm$anno_update)
```

```{r}
plot_data <- Myeloids@meta.data %>%
  group_by(Control_Cancer, anno_update) %>%
  summarise(Count = n()) %>%
  mutate(Percent = Count / sum(Count) * 100) %>%
  ungroup()
  

ggplot(plot_data, aes(x = Control_Cancer, y = Count, fill = anno_update)) +
  geom_bar(stat = "identity", position = "stack") +
  geom_text(aes(label = Count), position = position_stack(vjust = 0.5), size = 4)
  theme_minimal() +
  labs(x = "Count of cell type", y = "Cell Count", fill = "Cell Type") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(plot_data, aes(x = Control_Cancer, y = Percent, fill = anno_update)) +
  geom_bar(stat = "identity", position = "stack") +
  geom_text(aes(label = sprintf("%.1f%%", Percent)), position = position_stack(vjust = 0.5), size = 4)
  theme_minimal() +
  labs(x = "Count of cell type", y = "Cell Count", fill = "Cell Type") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```



```{r}
Myel.markers.APOE_high <- FindMarkers(Myeloids, ident.1 = "APOE high myeloid cells", test.use = "MAST", logfc.threshold = 0.1, verbose = F, min.pct = 0.1)
Myel.markers.FNC1_high <- FindMarkers(Myeloids, ident.1 = "FCN1 high myeloid cells", test.use = "MAST", logfc.threshold = 0.1, verbose = F, min.pct = 0.1)
Myel.markers.HLA_DQA1_high <- FindMarkers(Myeloids, ident.1 = "HLA-DQA1 high myeloid cells", test.use = "MAST", logfc.threshold = 0.1, verbose = F, min.pct = 0.1)

Myel.markers.APOE.vs.FCN1 <- FindMarkers(Myeloids, ident.1 = "APOE high myeloid cells", ident.2 = "FCN1 high myeloid cells", test.use = "MAST", logfc.threshold = 0.1, verbose = F, min.pct = 0.1)
Myel.markers.APOE.vs.HLA_DQA1 <- FindMarkers(Myeloids, ident.1 = "APOE high myeloid cells", ident.2 = "HLA-DQA1 high myeloid cells", test.use = "MAST", logfc.threshold = 0.1, verbose = F, min.pct = 0.1)
```

```{r}
Myel.markers.APOE_high -> temp
temp %>%
  filter(p_val_adj < 0.05) %>%
  filter(avg_log2FC > 0.58) -> up
dim(up)
write.csv(up,file = paste0(path,"APOE_high_021025/APOE_high_marker.csv"))
temp %>%
  filter(p_val_adj < 0.05) %>%
  filter(avg_log2FC < -0.58) -> dn
dim(dn)

Myel.markers.FNC1_high -> temp
temp %>%
  filter(p_val_adj < 0.05) %>%
  filter(avg_log2FC > 0.58) -> up
dim(up)
write.csv(up,file = paste0(path,"APOE_high_021025/FNC1_high_marker.csv"))
temp %>%
  filter(p_val_adj < 0.05) %>%
  filter(avg_log2FC < -0.58) -> dn
dim(dn)

Myel.markers.HLA_DQA1_high -> temp
temp %>%
  filter(p_val_adj < 0.05) %>%
  filter(avg_log2FC > 0.58) -> up
dim(up)
write.csv(up,file = paste0(path,"APOE_high_021025/HLA_DQA1_high_marker.csv"))
temp %>%
  filter(p_val_adj < 0.05) %>%
  filter(avg_log2FC < -0.58) -> dn
dim(dn)
```


# Volcanoplot
```{r}
source("~/projects/MK_Rcode/volcano_scdata.R")
vol1 <- volcano_scdata(Myel.markers.APOE_high,"APOE high vs other myeloids")
vol2 <- volcano_scdata(Myel.markers.FNC1_high,"FNC1 high vs other myeloids")
vol3 <- volcano_scdata(Myel.markers.HLA_DQA1_high,"HLA-DQA1 high vs other myeloids")

vol4 <- volcano_scdata(Myel.markers.APOE.vs.FCN1,"APOE high vs FCN1 high")
vol5 <- volcano_scdata(Myel.markers.APOE.vs.HLA_DQA1,"APOE high vs HLA-DQA1 high")
```


# GSEA
# APOE high
```{r}
sort_glist <- Myel.markers.APOE_high$avg_log2FC
names(sort_glist) <- rownames(Myel.markers.APOE_high)
sort_glist <- sort(sort_glist, decreasing = T)
gsea_Myel.APOE_high <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T)
```

```{r}
dotplot(gsea_Myel.APOE_high, showCategory=10, split=".sign") + facet_grid(.~.sign)
```

# FCN1 high
```{r}
sort_glist <- Myel.markers.FNC1_high$avg_log2FC
names(sort_glist) <- rownames(Myel.markers.FNC1_high)
sort_glist <- sort(sort_glist, decreasing = T)
gsea_Myel.FNC1_high <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T)
```

```{r}
dotplot(gsea_Myel.FNC1_high, showCategory=10, split=".sign") + facet_grid(.~.sign)
```

# HLA-DQA1 high
```{r}
sort_glist <- Myel.markers.HLA_DQA1_high$avg_log2FC
names(sort_glist) <- rownames(Myel.markers.HLA_DQA1_high)
sort_glist <- sort(sort_glist, decreasing = T)
gsea_Myel.HLA_DQA1_high <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T)
```

```{r}
dotplot(gsea_Myel.HLA_DQA1_high, showCategory=10, split=".sign") + facet_grid(.~.sign)
```

# APOE high vs FCN1 high
```{r}
sort_glist <- Myel.markers.APOE.vs.FCN1$avg_log2FC
names(sort_glist) <- rownames(Myel.markers.APOE.vs.FCN1)
sort_glist <- sort(sort_glist, decreasing = T)
gsea_Myel.APOE.vs.FNC1 <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T)
```

```{r}
dotplot(gsea_Myel.APOE.vs.FNC1, showCategory=10, split=".sign") + facet_grid(.~.sign)
```

# APOE high vs HLA-DQA1 high
```{r}
sort_glist <- Myel.markers.APOE.vs.HLA_DQA1$avg_log2FC
names(sort_glist) <- rownames(Myel.markers.APOE.vs.HLA_DQA1)
sort_glist <- sort(sort_glist, decreasing = T)
gsea_Myel.APOE.vs.HLA_DQA1 <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T)
```

```{r}
dotplot(gsea_Myel.APOE.vs.HLA_DQA1, showCategory=10, split=".sign") + facet_grid(.~.sign)
```

```{r, fig.height= 10, fig.width= 8}
temp <- Myel.markers.APOE_high
temp %>%
  filter(p_val_adj < 0.05) %>%
  filter(avg_log2FC > 1) -> tm
a <- tm$avg_log2FC
names(a) <- rownames(tm)
a <- sort(a, decreasing = T)

VlnPlot(Myeloids, features = names(a)[1:10], ncol = 4)
```

```{r}
DotPlot(Myeloids, features = names(a)[1:10]) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_colour_gradient2(low = "blue", mid = "gray", high = "red", midpoint = 0)
```

```{r, fig.height= 10, fig.width= 8}
temp <- Myel.markers.APOE.vs.FCN1
temp %>%
  filter(p_val_adj < 0.05) %>%
  filter(avg_log2FC > 1) -> tm
a <- tm$avg_log2FC
names(a) <- rownames(tm)
a <- sort(a, decreasing = T)

VlnPlot(Myeloids, features = names(a)[1:10], ncol = 4)
```


```{r}
DotPlot(Myeloids, features = names(a)[1:10]) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_colour_gradient2(low = "blue", mid = "gray", high = "red", midpoint = 0)
```

```{r, fig.height= 10, fig.width= 8}
temp <- Myel.markers.APOE.vs.HLA_DQA1
temp %>%
  filter(p_val_adj < 0.05) %>%
  filter(avg_log2FC > 1) -> tm
a <- tm$avg_log2FC
names(a) <- rownames(tm)
a <- sort(a, decreasing = T)

VlnPlot(Myeloids, features = names(a)[1:10], ncol = 4)
```


```{r}
DotPlot(Myeloids, features = names(a)[1:10]) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_colour_gradient2(low = "blue", mid = "gray", high = "red", midpoint = 0)
```


```{r, fig.height= 10, fig.width= 8}
temp <- Myel.markers.FNC1_high
temp %>%
  filter(p_val_adj < 0.05) %>%
  filter(avg_log2FC > 1) -> tm
a <- tm$avg_log2FC
names(a) <- rownames(tm)
a <- sort(a, decreasing = T)

VlnPlot(Myeloids, features = names(a)[1:10], ncol = 4)
```

```{r}
DotPlot(Myeloids, features = names(a)[1:10]) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_colour_gradient2(low = "blue", mid = "gray", high = "red", midpoint = 0)
```

```{r, fig.height= 10, fig.width= 8}
temp <- Myel.markers.HLA_DQA1_high
temp %>%
  filter(p_val_adj < 0.05) %>%
  filter(avg_log2FC > 1) -> tm
a <- tm$avg_log2FC
names(a) <- rownames(tm)
a <- sort(a, decreasing = T)

VlnPlot(Myeloids, features = names(a)[1:10], ncol = 4)
```


```{r}
DotPlot(Myeloids, features = names(a)[1:10]) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_colour_gradient2(low = "blue", mid = "gray", high = "red", midpoint = 0)
```

```{r}
tm <- Myel.markers.APOE_high %>%
  filter(p_val_adj < 0.05) %>%
  arrange(desc(avg_log2FC)) %>%
  slice_head(n=10)
top10 <- rownames(tm)
tm <- Myel.markers.FNC1_high %>%
  filter(p_val_adj < 0.05) %>%
  arrange(desc(avg_log2FC)) %>%
  slice_head(n=10)
top10 <- c(top10, rownames(tm))
tm <- Myel.markers.HLA_DQA1_high %>%
  filter(p_val_adj < 0.05) %>%
  arrange(desc(avg_log2FC)) %>%
  slice_head(n=10)
top10 <- c(top10, rownames(tm))
```


```{r, fig.height= 8, fig.width= 12}
fig1 <- DoHeatmap(Myeloids, features = top10, label = F) +
  scale_fill_gradient2(low = "blue", mid = "lightgray", high = "red", midpoint = 0)
fig1
fig2 <- DoHeatmap(Myeloids, features = top10, label = F)
fig2
```

```{r, fig.height= 4, fig.width=10}
fig3 <- DotPlot(Myeloids, features = top10) + 
  scale_color_gradient2(low = "blue", mid = "lightgray", high = "red", midpoint = 0) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
fig3
```


```{r}
pdf(file = paste0(path,"APOE_high_021025/heatmap_022525.pdf"), height = 6, width = 10)
fig1
fig2
dev.off()
```

```{r}
pdf(file = paste0(path,"APOE_high_021025/dotplot_022525.pdf"), height = 4, width = 10)
fig3
dev.off()
```













